language: node_js
node_js:
- '6'
before_script:
- npm install -g webpack
- npm install -g codecov
before_deploy:
- npm run deploy
deploy:
  provider: heroku
  api_key: e8b086d1-b5ca-4504-8baf-7f55a085b37d
  app: jalgoarena-ui-koscinsa
  on:
    repo: kostekman/JAlgoArena-UI
    tags: false
addons:
    code_climate:
        repo_token: 9e2995be6eae3d6663fd00f8db738c4bf306f9f7779c8f1c4fb0f5d0d56c17e0